# Site settings 配置站点
title: "Lfalive's Blog"
description: 'Studying at Huazhong University of Science and Technology.'
keyword: "Lfalive, Lfalive's Blog, 前端, 前端开发, 前端博客, 设计"
url: 'https://lfalive.github.io/' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Footer
footer:
  since: 2018

# Author 配置博主信息
author: 'Lfalive'
nickname: 'NOnickname'
bio: 'Student'
avatar: '/assets/img/profile.jpg'

# Search
search: true

# Night mode
nightMode: true

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ["weibo","qq","wechat","douban","qzone","linkedin","facebook","twitter","google"]

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: '//github.com/lfalive'
  email: '//542679373@qq.com'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 9 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 7
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
